{{- if not .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: darwin-store
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.auth.password | b64enc | quote }}
{{- end }}
